<a href="https://colab.research.google.com/github/tiasaxena/ML-Notebooks/blob/main/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

### 1. Tensor Basics

In [6]:
# Initialize
x = tf.constant(3, shape=(2, 3), dtype=tf.int8)
print(x)

tf.Tensor(
[[3 3 3]
 [3 3 3]], shape=(2, 3), dtype=int8)


In [4]:
x = tf.constant([[1, 2, 4], [5, 6, 8], [0, 2, 3]], shape=(3, 3), dtype=tf.float64)
print(x)

tf.Tensor(
[[1. 2. 4.]
 [5. 6. 8.]
 [0. 2. 3.]], shape=(3, 3), dtype=float64)


In [9]:
# Identity Matrix
x = tf.eye(5)
print(x)

tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]], shape=(5, 5), dtype=float32)


In [11]:
x = tf.ones(shape=(2, 3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [13]:
x = tf.zeros(shape=(2, 3, 5))
print(x)

tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(2, 3, 5), dtype=float32)


In [18]:
# Generate 2X3 matrix of random nos. from a normal distribution
x = tf.random.normal(shape=(2, 3), mean=0, stddev=1)
print(x)
print(tf.cast(x, dtype=tf.float64))

tf.Tensor(
[[ 0.4701384   1.3799273  -1.0573863 ]
 [ 0.2908866   0.1773116  -0.45897686]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 0.4701384   1.37992728 -1.05738628]
 [ 0.29088661  0.1773116  -0.45897686]], shape=(2, 3), dtype=float64)


In [24]:
# generate numbers with equal probability
x = tf.random.uniform(shape=(2, 1), minval=0, maxval=1)
print(x)

tf.Tensor(
[[0.74196017]
 [0.7887168 ]], shape=(2, 1), dtype=float32)


In [25]:
x = tf.range(9)
y = tf.range(0, 10, 3)
x, y

(<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 3, 6, 9], dtype=int32)>)

In [26]:
# Operations
x = tf.constant([1, 2, 3])
y = tf.constant([9, 8, 7])

print(x + y)
print(tf.add(x, y))

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [27]:
print(x - y)
print(tf.subtract(x, y))

tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)
tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)


In [28]:
print(x / y)
print(tf.divide(x, y))

tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)
tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)


In [29]:
print(x * y)
print(tf.multiply(x, y))

tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)
tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)


In [34]:
print(tf.tensordot(x, y, axes=0)) # axes 0 computes all pairwise combinations
print(tf.tensordot(x, y, axes=1)) # azes = 1 computes the dot product

tf.Tensor(
[[ 9  8  7]
 [18 16 14]
 [27 24 21]], shape=(3, 3), dtype=int32)
tf.Tensor(46, shape=(), dtype=int32)


In [35]:
print(x ** 5)

tf.Tensor([  1  32 243], shape=(3,), dtype=int32)


In [36]:
a = tf.random.normal(shape=(2, 3))
b = tf.random.normal(shape=(3, 2))

print(a @ b)

tf.Tensor(
[[ 2.2573762  -1.4725755 ]
 [-1.95708     0.44149977]], shape=(2, 2), dtype=float32)


In [38]:
# Indexing
x = tf.constant([0, 1, 2, 3, 4, 5, 6, 7, 8])
print(x[:])
print(x[1:])
print(x[1:3])
print(x[::2]) # The slicing syntax is [start:stop:step] --> [0, n, step = 2]
print(x[::-1]) # The slicing syntax is [start:stop:step] --> [0, n, step = -1] --> reverse

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor([1 2 3 4 5 6 7 8], shape=(8,), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)
tf.Tensor([8 7 6 5 4 3 2 1 0], shape=(9,), dtype=int32)


In [39]:
x = tf.constant([[1, 2], [3, 4], [5, 6]])

print(x[0, :])
print(x[0:2, :])

tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [42]:
# Reshaping
x = tf.range(8)
print(x)
x = tf.reshape(x, (2, 4))
print(x)
x = tf.transpose(x, perm=[1, 0])
print(x)

tf.Tensor([0 1 2 3 4 5 6 7], shape=(8,), dtype=int32)
tf.Tensor(
[[0 1 2 3]
 [4 5 6 7]], shape=(2, 4), dtype=int32)
tf.Tensor(
[[0 4]
 [1 5]
 [2 6]
 [3 7]], shape=(4, 2), dtype=int32)
